export enum AgentEvent {
  STATE_CHANGED = 'STATE_CHANGED',
  STEP_STARTED = 'STEP_STARTED',
  STEP_COMPLETED = 'STEP_COMPLETED',
  ERROR = 'ERROR',
  LOG_ADDED = 'LOG_ADDED',
  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_FINISHED = 'SESSION_FINISHED'
}
